name: ELT Pipeline CI

on:
    push:
        branches: ["main"]
    schedule:
        - cron: "0 7 * * *"

jobs:
    run-etl:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: "3.11"

            - name: Install dependencies
              run: pip install -r requirements.txt

            - name: Run ETL script
              run: python main.py

            - name: Upload results artifact
              uses: actions/upload-artifact@v3
              with:
                name: sales_summary
                path: data/sales_summary.csv

            - name: Run tests
              run: pytest -v
            